all:
  vars:
    # --- VARIABLES GLOBALES DE CONEXIÓN ---
    ansible_user: automation             # Usuario SSH estándar
    ansible_ssh_private_key_file: "~/.ssh/id_rsa_migration"
    ansible_python_interpreter: auto_silent  # Detecta Python 2 vs 3 automáticamente
    
    # --- VARIABLES DE MIGRACIÓN ---
    migration_approver: "SysAdmin Team"
    backup_required: true

  children:
    # ---------------------------------------------------------
    # GRUPO 1: SEGMENTACIÓN POR ENTORNO (DEV / STAGING / PROD)
    # ---------------------------------------------------------
    produccion:
      vars:
        risk_tolerance: "zero"           # Variable lógica para tus playbooks
      children:
        prod_databases:
          vars:
            service_criticality: "high"
          hosts:
            db-master-01.empresa.local:
            db-slave-01.empresa.local:
        
        prod_webservers:
          hosts:
            web-fe-01.empresa.local:
            web-fe-02.empresa.local:

    desarrollo:
      vars:
        risk_tolerance: "high"
      hosts:
        dev-app-01.empresa.local:
        dev-db-01.empresa.local:

    # ---------------------------------------------------------
    # GRUPO 2: SEGMENTACIÓN TÉCNICA (SISTEMAS LEGACY)
    # Aquí agrupamos TODO lo que sea CentOS 7 / RHEL 7
    # ---------------------------------------------------------
    legacy_candidates:
      vars:
        leapp_target_version: "8.10"     # Versión objetivo de RHEL
        convert2rhel_enabled: true
      children:
        # Cruce de grupos: Estos hosts ya están definidos arriba, 
        # pero aquí los agrupamos por su OS para la migración.
        centos7_servers:
          hosts:
            db-master-01.empresa.local:  # Mismo host, diferente agrupación
            web-fe-01.empresa.local:
            dev-app-01.empresa.local:

    # ---------------------------------------------------------
    # GRUPO 3: OTROS SISTEMAS (NO MIGRABLES CON LEAPP)
    # ---------------------------------------------------------
    debian_family:
      vars:
        ansible_become_method: sudo
      children:
        ubuntu_servers:
          hosts:
            monitor-01.empresa.local:
            logs-01.empresa.local:

    # ---------------------------------------------------------
    # GRUPO 4: EXCLUIDOS (NO TOCAR BAJO NINGUNA CIRCUNSTANCIA)
    # ---------------------------------------------------------
    blacklisted:
      hosts:
        legacy-erp-solaris.empresa.local:
   #-----------------------------------------------------------
   # Si pasas por un servidor bastión. Si este es tu caso, 
   # añade esto al final de tu archivo inventory/hosts.yml 
   # (dentro de all: vars o en un grupo específico):       
   # ---------------------------------------------------------
   # # Configuración para pasar a través de un Bastión
   # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q automation@bastion.empresa.local"'
