# Ansible Migration Assessment - Example Inventory
all:
  children:
    legacy_servers:
      hosts:
        # Add your CentOS 7 servers here
        # centos7-server1:
        #   ansible_host: 192.168.1.10
        #   ansible_user: admin
        # centos7-server2:
        #   ansible_host: 192.168.1.11
        #   ansible_user: admin
    
    rhel_servers:
      hosts:
        # Add your RHEL 7 servers here
        # rhel7-server1:
        #   ansible_host: 192.168.1.20
        #   ansible_user: admin
    
    debian_servers:
      hosts:
        # Add your Debian/Ubuntu servers here
        # ubuntu18-server1:
        #   ansible_host: 192.168.1.30
        #   ansible_user: admin
  
  vars:
    # Common variables
    ansible_python_interpreter: /usr/bin/python3
    # ansible_become_password: your_sudo_password
